//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jipp_Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opis_Bron
    {
        public int Id { get; set; }
        public string Producent { get; set; }
        public string Model { get; set; }
        public string Kaliber { get; set; }
        public string Typ { get; set; }
        public string Opis { get; set; }
    }
}
