//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jipp_Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opis_Stanowiska
    {
        public int ID { get; set; }
        public string Kulochwyt { get; set; }
        public Nullable<int> Odleglosc_tarcz { get; set; }
        public string Opis { get; set; }
    }
}
